[package]
name = "yaml-rt-wasm"
description = "Browser bindings for the yaml-rt command playground"
edition = "2024"
version = "0.2.2"
license = "MIT OR Apache-2.0"
authors = ["Hannes De Valkeneer <hannes@de-valkeneer.be>"]
readme = "../../README.md"
repository = "https://github.com/hdevalke/yaml-rt"
rust-version = "1.96"
publish = false

[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[lib]
crate-type = ["cdylib", "rlib"]
name = "yaml_rt_wasm"
path = "src/lib.rs"

[dependencies]
wasm-bindgen.workspace = true
yaml-rt-core.workspace = true
yaml-rt-rfc9535.workspace = true
